// Generated from images used by indexable page components.
export const sitemapImages: Record<string, string[]> = {
  "/": ["https://www.junkmycaryyc.ca/images/junkmycar-banner.png","https://www.junkmycaryyc.ca/jmc-imgs/purchase-19.jpeg","https://www.junkmycaryyc.ca/jmc-imgs/purchase-23.jpeg"],
  "/about": ["https://www.junkmycaryyc.ca/jmc-imgs/purchase-23.jpeg"],
  "/blog/how-to-sell-luxury-cars-for-cash-calgary": ["https://www.junkmycaryyc.ca/images/blog/sell-luxury-car-calgarypng.png"],
  "/blog/selling-a-car-and-taxes-alberta": ["https://www.junkmycaryyc.ca/images/blog/selling-a-car-and-taxes.png"],
  "/cash-for-cars-airdrie": ["https://www.junkmycaryyc.ca/images/junkmycar-banner.png","https://www.junkmycaryyc.ca/jmc-imgs/purchase-23.jpeg","https://www.junkmycaryyc.ca/jmc-imgs/purchase-26.jpeg"],
  "/cash-for-cars-cochrane": ["https://www.junkmycaryyc.ca/images/junkmycar-banner.png","https://www.junkmycaryyc.ca/jmc-imgs/purchase-19.jpeg","https://www.junkmycaryyc.ca/jmc-imgs/purchase-23.jpeg"],
  "/cash-for-cars-high-river": ["https://www.junkmycaryyc.ca/images/junkmycar-banner.png","https://www.junkmycaryyc.ca/jmc-imgs/purchase-19.jpeg","https://www.junkmycaryyc.ca/jmc-imgs/purchase-23.jpeg"],
  "/cash-for-cars-lethbridge": ["https://www.junkmycaryyc.ca/images/junkmycar-banner.png","https://www.junkmycaryyc.ca/jmc-imgs/purchase-23.jpeg","https://www.junkmycaryyc.ca/jmc-imgs/purchase-26.jpeg"],
  "/cash-for-cars-okotoks": ["https://www.junkmycaryyc.ca/images/junkmycar-banner.png","https://www.junkmycaryyc.ca/jmc-imgs/purchase-23.jpeg","https://www.junkmycaryyc.ca/jmc-imgs/purchase-26.jpeg"],
  "/cash-for-cars-olds": ["https://www.junkmycaryyc.ca/images/junkmycar-banner.png","https://www.junkmycaryyc.ca/jmc-imgs/purchase-23.jpeg","https://www.junkmycaryyc.ca/jmc-imgs/purchase-26.jpeg"],
  "/cash-for-cars-red-deer": ["https://www.junkmycaryyc.ca/images/junkmycar-banner.png","https://www.junkmycaryyc.ca/jmc-imgs/purchase-19.jpeg","https://www.junkmycaryyc.ca/jmc-imgs/purchase-23.jpeg"],
  "/junk-my-car-banff": ["https://www.junkmycaryyc.ca/images/junkmycar-banner.png","https://www.junkmycaryyc.ca/jmc-imgs/purchase-19.jpeg","https://www.junkmycaryyc.ca/jmc-imgs/purchase-23.jpeg"],
  "/junk-my-car-brooks": ["https://www.junkmycaryyc.ca/images/junkmycar-banner.png","https://www.junkmycaryyc.ca/jmc-imgs/purchase-19.jpeg","https://www.junkmycaryyc.ca/jmc-imgs/purchase-23.jpeg"],
  "/junk-my-car-canmore": ["https://www.junkmycaryyc.ca/images/junkmycar-banner.png","https://www.junkmycaryyc.ca/jmc-imgs/purchase-19.jpeg","https://www.junkmycaryyc.ca/jmc-imgs/purchase-23.jpeg"],
  "/junk-my-car-chestermere": ["https://www.junkmycaryyc.ca/images/junkmycar-banner.png","https://www.junkmycaryyc.ca/jmc-imgs/purchase-19.jpeg","https://www.junkmycaryyc.ca/jmc-imgs/purchase-23.jpeg"],
  "/junk-my-car-diamond-valley": ["https://www.junkmycaryyc.ca/images/junkmycar-banner.png","https://www.junkmycaryyc.ca/jmc-imgs/purchase-23.jpeg","https://www.junkmycaryyc.ca/jmc-imgs/purchase-26.jpeg"],
  "/junk-my-car-didsbury": ["https://www.junkmycaryyc.ca/images/junkmycar-banner.png","https://www.junkmycaryyc.ca/jmc-imgs/purchase-23.jpeg","https://www.junkmycaryyc.ca/jmc-imgs/purchase-26.jpeg"],
  "/junk-my-car-drumheller": ["https://www.junkmycaryyc.ca/images/junkmycar-banner.png","https://www.junkmycaryyc.ca/jmc-imgs/purchase-19.jpeg","https://www.junkmycaryyc.ca/jmc-imgs/purchase-23.jpeg"],
  "/junk-my-car-medicine-hat": ["https://www.junkmycaryyc.ca/images/junkmycar-banner.png","https://www.junkmycaryyc.ca/jmc-imgs/purchase-19.jpeg","https://www.junkmycaryyc.ca/jmc-imgs/purchase-23.jpeg"],
  "/junk-my-car-strathmore": ["https://www.junkmycaryyc.ca/images/junkmycar-banner.png","https://www.junkmycaryyc.ca/jmc-imgs/purchase-23.jpeg","https://www.junkmycaryyc.ca/jmc-imgs/purchase-26.jpeg"],
  "/services/cash-for-junk-cars-calgary": ["https://www.junkmycaryyc.ca/images/junkmycar-banner.png","https://www.junkmycaryyc.ca/jmc-imgs/purchase-21.jpeg","https://www.junkmycaryyc.ca/jmc-imgs/purchase-22.jpeg"],
  "/services/cash-for-scrap-cars-calgary": ["https://www.junkmycaryyc.ca/images/junkmycar-banner.png","https://www.junkmycaryyc.ca/jmc-imgs/purchase-18.jpeg","https://www.junkmycaryyc.ca/jmc-imgs/purchase-20.jpeg"],
  "/services/junk-car-removal-calgary": ["https://www.junkmycaryyc.ca/images/junkmycar-banner.png","https://www.junkmycaryyc.ca/jmc-imgs/purchase-19.jpeg","https://www.junkmycaryyc.ca/jmc-imgs/purchase-23.jpeg"],
  "/services/scrap-car-removal-calgary": ["https://www.junkmycaryyc.ca/images/junkmycar-banner.png","https://www.junkmycaryyc.ca/jmc-imgs/purchase-23.jpeg","https://www.junkmycaryyc.ca/jmc-imgs/purchase-24.jpeg"],
};
